### ISSUE TITLE
About link to multiple/backup passkeys

### ISSUE THREAD

**Issue by iketiunn** [gavinsawyer/firebase-web-authn#13]
Hi Gavin,

Thank you for your hard work on this extension!

I noticed that in the current version (10.4.1) of `firebase-web-authn`, it is possible for a user account to link both a primary and a secondary passkey.

I wanted to ask for your opinion on extending support to link more than two passkeys, similar to how GitHub or Vercel handle it. Do you think implementing this feature would be suitable for this extension?

**Comment by gavinsawyer** [comment]
Hi Ike,

Sorry, there isn’t a way to do this with my extension barring a rewrite. When I added backups I was way more concerned with what it meant for security. The app segment I had in mind is fully automated and trustless meaning no permanent account loss and no customer service.

My idea was to have the primary key self-destruct when the backup was used and to require the backup be present to change or remove it. This way account security would ultimately be backed by property law and physical security but users could still leave the keys behind in a safe location. If a user’s device is compromised, they could use the backup key to regain access. This seemed overcomplicated for default behavior so I left it up to developers to implement trustless auth by having the extension write to Firestore which passkey was used last.

Since all that happened it seems user expectations have changed and in retrospect it would have made more sense to allow any number of passkeys. I also was focused on maintaining backwards compatibility when adding backup support, but I’m open to adding support for unlimited passkeys in a new version with breaking API changes.

**Comment by iketiunn** [comment]
Thank you for sharing your thoughts! Your explanation was very detailed, and it gave me a deeper understanding of your considerations during the design process. I appreciate your efforts to balance security and user experience. I'm looking forward to the future updates that will allow support for more passkey management!
