### ISSUE TITLE
API does not support multiple/backup passkeys

### ISSUE THREAD

**Issue by czabaj** [gavinsawyer/firebase-web-authn#3]
I just tested your extension and I must thank you for the excellent work you have done! The installation was smooth and the extra steps needed were clear and everything works flawlessly 🙇 

I'm new to WebAuthn, I'm playing with it on my pet project to gain some experience. I want to use WebAuthn primarily as a convenience for my users, so they can log in with platform authenticator (FaceID, TouchID), my project is a PWA for the beer club, so nothing super sensitive 😄 

I noticed that when I link the account with the passphrase, it creates an entry in the `webAuthnUsers` Firestore collection with the ID of the account UID, what happens if the same account links a new passphrase, e.g. from a different device, let's say their devices are not synced, it might be one device from work and one home device, both with platform authenticators. I did not test that yet, but I think the new passphrase will replace the old one?

**Comment by gavinsawyer** [comment]
Hi Václav, thanks for your kind message! When attempting to create a passkey for an account that already has one, you're given a `no-op` error. If you want to replace it, you would have to be signed in and perform `unlinkPasskey()` first.

This wasn't something I thought of because passkey managers don't recognize multiple passkeys per account. There's no way for the app to tell if the second passkey being created is overwriting the first one or if it's being stored in a different browser/YubiKey. This wasn't necessarily a design choice, but it encourages breaking up the process into two steps, as there is no way for the app to delete a passkey from the user's device, and `unlinkPasskey()` should be accompanied by asking the user to do this so it no longer appears as a sign-in option.

I really recommend keeping to the principle of one user one passkey, just like passwords. I can see the appeal when needing to add a backup YubiKey, though, so I'd be happy to add support in v10. My only concern is which passkey to trust in a backup scenario. Should you be able to delete backup passkeys from your account, assuming that they're there in case the primary one gets stolen? If not, what if the backup gets stolen?, etc. Avoiding these questions and pretending users are trustworthy is probably why we don't have native support yet. /s

Of course, if you just want multiple valid passkeys per account that functionality will be implemented first as it's easier, but both multi-passkey and backup passkey functionality would be turned off by default for the reasons I discussed.

**Comment by gavinsawyer** [comment]
> let's say their devices are not synced, it might be one device from work and one home device, both with platform authenticators

Also, to this point I'd say this is the reason why as a user, whatever passkey manager is native to your phone is best. I'm an iCloud Keychain user and I'm able to log in on any device. When the `signInWithPasskey()` dialog comes up on a browser that doesn't have a passkey saved, it asks you to either try a YubiKey or scan a QR code from your phone to sign in over Bluetooth.

**Comment by czabaj** [comment]
> I really recommend keeping to the principle of one user one passkey, just like passwords.

I tend to agree and it is not a huge limitation, but still.

The reason I ask is that I don't implement the WebAuthn as it is meant to be, i.e. as a primary, and only method for signing in. I'm using WebAuthn as a way to allow my users to sign in with biometric authenticators, but they have to sign in with a traditional email/password or OAuth (Google, Apple) first - I want their e-mails for recovery.

I learned from [this Yubico video](https://www.youtube.com/watch?v=mvJ-XeFgct8), that recovery in WebAuthn is not yet a solved problem. If you use _just_ WebAuthn for signing in, it is super secure, phishing-proof, but what if you loose or break your key? If you use Apple platform authenticators, then your private key is (probably?) backed up in the cloud and in the event you lose your phone you can recover, but if you use Yubikey or some other hardware authenticators, you must use at least two authenticators - one as your primary device and one as a backup - this implies that more than one passphrases should be supported in any WebAuthn implementation.
