### ISSUE TITLE
Question: Detect if user has registered passphrase for the domain

### ISSUE THREAD

**Issue by czabaj** [gavinsawyer/firebase-web-authn#5]
I learned that for privacy reasons it is impossible to detect if the device has a stored passphrase for the app, i.e. it is impossible to test whether the user on my sing-in page can sign-in with WebAuthn.

The proposed best practice is probably to show a <kbd>Sign in with WebAuthn</kbd> button, which will _try_ to sign in and when that fails, point the users to a _sign-up_ with WebAuthn option.

In my app, I don't want my users to _sign-up_ with WebAuthn, because I'm using the WebAuthn just as a hack to allow _sign-in_ with biometrics, so the WebAuthn is there just as a secondary and more convenient way of signing in. Since I cannot detect whether the user device is already registered, I'm storing that information in `localStorage` and I offer <kbd>Sign in with WebAuthn</kbd> button only when the `localStorage` item is set. This means, that when my user clears the browser data, they have to sign in with some other, primary method first, and then I offer them the WebAuthn during the onboarding screen (even if they have the passphrase set-up already 🤷 ).

It is not a huge deal, I'm able to work around this limitation, but still, are you aware of any way how to detect that the passphrase already exists?

**Comment by gavinsawyer** [comment]
I'm not aware of a way to detect existing passkeys and this would not be the best course of action for one main reason: You can still log in on a device without a passkey saved. The best practice is to always show the button if the browser supports WebAuthn: `("credentials" in navigator) ? yes() : no()`. This is because even when no passkey is saved, the interface will allow you to try a YubiKey or scan a QR code from a device that does have the passkey saved:

<img width="1199" src="https://github.com/gavinsawyer/firebase-web-authn/assets/6238591/efc67629-d9be-498e-b8eb-2c8c619d0a99">
